### ISSUE TITLE
请教一下poll_info字段

### ISSUE THREAD

**Issue by just4fun** [UESTC-BBS/API-Docs#11]
poll_status跟type，这两个能全部列举一下状态吗？

**Comment by fangjue** [comment]
poll_status: mobcent/app/models/DzForumThread.php 搜索 STATUS_VOTE_*（1：已投票；2：可以投票；3：没有权限；4：投票已结束）。
type 最多选几项？

**Comment by just4fun** [comment]
我靠站长回复恁快？
怎么看那个php文件？直接论坛地址＋这个文件会得到Access Denied。

**Comment by fangjue** [comment]
http://addon.discuz.com/?@appbyme_app.plugin.doc/install 下载 mobcent.zip。

**Comment by just4fun** [comment]
福得紧。
