### ISSUE TITLE
是否有用户发表的主题跟回复列表的接口？

### ISSUE THREAD

**Issue by just4fun** [UESTC-BBS/API-Docs#12]
- 用户发表过的主题列表
- 用户回复过的主题列表

`forum/topiclist` 貌似只能获取某个版块的主题列表。

**Comment by fangjue** [comment]
`user/topiclist`

**Comment by just4fun** [comment]
找到了，感谢上次提供的mobcent源码地址。
主要还是不熟悉PHP。
