### ISSUE TITLE
forum/topiclist 下的 topOrder 参数未生效

### ISSUE THREAD

**Issue by SeanChense** [UESTC-BBS/API-Docs#5]
topOrder 填 0 一样返回置顶贴，并没有生效。

**Comment by fangjue** [comment]
一般不加特别说明，“布尔”类型的参数默认都是 0（false），设置成 1 才表示 true。

**Comment by SeanChense** [comment]
> topOrder 0（不返回置顶帖，默认）, 1（返回本版置顶帖）, 2（返回分类置顶帖）, 3（返回全局置顶帖）。置顶帖包含在 topTopicList 字段中。

我理解的是：
- 0 就是不返回置顶贴，且是默认的；
- 1 返回置顶
- 2 返回分类置顶帖
- 3 返回全局置顶帖

**Comment by SeanChense** [comment]
是我发的请求有问题
我应该仔细学习下 http 的知识
