### ISSUE TITLE
About `forum/forumlist`

### ISSUE THREAD

**Issue by just4fun** [UESTC-BBS/API-Docs#9]
获取板块列表的这个[API](http://bbs.uestc.edu.cn/mobcent/app/web/index.php?r=forum/forumlist)，response的json里有个`<div>`，里面还有个`<img>`……

反序列化不成功，如何破？我是js访问。

**Comment by fangjue** [comment]
具体是怎么调用的？forumlist 返回 list，好像没有 response。

**Comment by just4fun** [comment]
你直接打开[这个链接](http://bbs.uestc.edu.cn/mobcent/app/web/index.php?r=forum/forumlist)就可以看到，list里有张图片。

**Comment by fangjue** [comment]
http://bbs.uestc.edu.cn/forum.php?mod=redirect&goto=findpost&ptid=1561025&pid=27730787

已在河畔上回答。

**Comment by fangjue** [comment]
http://bbs.uestc.edu.cn/forum.php?mod=redirect&goto=findpost&ptid=1561025&pid=27730787
